### ISSUE TITLE
Device is present in both iFixit Devices and Grab Bag

### ISSUE THREAD

**Issue by davidrans** [danielcliu/grab-bag-project#1]
Problem
---
Once a device is moved to the user's Grab Bag, it still remains in the list of iFixit devices:
![image](https://user-images.githubusercontent.com/806152/100157628-b1853500-2e5f-11eb-9b66-cd8fd4d200dc.png)

Do This
---
Moving a device to the grab bag should remove it from the list of iFixit Devices.

**Comment by danielcliu** [comment]
@davidrans When a devices is removed, should the page still have 24 devices by sliding the next device into the page or should the page go down to 23 devices displayed? When a device is removed from the Grab Bag should it be put back into the iFixitDevices list where it was in the list returned by the API?

**Comment by davidrans** [comment]
Good questions!

> When a devices is removed, should the page still have 24 devices by sliding the next device into the page or should the page go down to 23 devices displayed?

Yeah, I think it'd be great if the list of devices was always populated with 24 devices.

> When a device is removed from the Grab Bag should it be put back into the iFixitDevices list where it was in the list returned by the API?

Yeah, that'd be a good user experience, I think.
